### ISSUE TITLE
Restricted setting

### ISSUE THREAD

**Issue by barbe6** [aghontpi/ad-silence#103]
Hi,
On android 13.1 (ArrowOS) when I try to grant permission to notification access, for Ad-silence the switch is disabled, and I get a message that this setting is not available. For other apps in the same list (Google Play Services, Spotify, Amazon Alexa ... ) the setting is enabled and I can switch it on/off.
I have searched though settings, including developer settings and cannot find a clue for this. Do you think this is related to ad-silence or to android 13.1?
Thanks

**Comment by aghontpi** [comment]
Hi @barbe6 thanks for bringing this up, It is part of android 13 and up, ref link: https://support.google.com/android/answer/12623953?sjid=3702608675861705680-AP#allowrestrictedsettings

Have tested this behaviour on a pixel running android 14 stable, 
- issue does not happen if app is installed from play store, 
- issue occurs if you install the app from GitHub release (likely because of the different app signature than playstore)
- this issue does not occur on emulators.

**Solution:** 
- install the app from playstore

(or)

- You can override this behaviour by going to app settings of ad-silence, pressing the 3 dots and then allowing, ref the video below. 

**request:**
I'm not sure how this will work on ArrowOS. could you pls check if there is an option similar to the one in video and report it back. 


https://github.com/aghontpi/ad-silence/assets/18617846/db09140a-de60-45d4-aed8-cc6ffedaac50




**todo: a reference for me**
I'll have to include this as a note in the app UI so others can know what's going on..

**Comment by aghontpi** [comment]
@barbe6 again huge thanks for bringing this up, looks like this will be a major issue in upcoming android versions.

**Comment by barbe6** [comment]
Thanks,
I confirm that I could allow access. The option was indeed hidden under the three dots ... in the app

**Comment by aghontpi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add info for unable to grant permission.](https://trello.com/c/Z4buaSHz/83-add-info-for-unable-to-grant-permission)

**Comment by aghontpi** [comment]
Added a wiki page, added a link to that wiki page on the app. no other workarounds for now.

installing from playstore still works for me though.
