### ISSUE TITLE
Pandora incompatibility

### ISSUE THREAD

**Issue by QuinnLion** [aghontpi/ad-silence#47]
Methinks Pandora has made a workaround that pauses ads when the device is muted. :/

**Comment by aghontpi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pandora pauses music while muting](https://trello.com/c/hiKMS7gn/51-pandora-pauses-music-while-muting)

**Comment by aghontpi** [comment]
thanks for the report @QuinnLion

**Comment by aghontpi** [comment]
Have tested the same on extended listening sessions, this happens when you want to earn skips by watching ads.

on normal playbacks, the advertisements are muted without issues.

**ref screenshots, a station was playing, ad plays (gets muted), next song plays (audio is restored)**

<img src="https://github.com/aghontpi/ad-silence/assets/18617846/2293b1f6-7e1d-4398-85c3-2c4896b31f82" height="480"/>

<img src="https://github.com/aghontpi/ad-silence/assets/18617846/ba693576-89cf-496a-961e-b3424d892981" height="480"/>

**ref video**

https://github.com/aghontpi/ad-silence/assets/18617846/921fb4b8-1138-4998-aedf-ceb381399ab6


more: 

while watching ads to earn skips, the notification title is not updated, only 1/10 tries updates the notification title with "skip limit exceeded", so this can't be implemented for earning skips.


(tested on a14, pixel device)
<img height="480" src="https://github.com/aghontpi/ad-silence/assets/18617846/157b1a1b-bff3-4623-b6f7-731fa46c6c5c"/>
