### ISSUE TITLE
Blocking YouTube Ads

### ISSUE THREAD

**Issue by HonestAbe7** [aghontpi/ad-silence#9]
Since you wrote you would be open to adding more streaming services, I was wondering if you could please also block YouTube ads? I don't use the Android app but just go through the web and I use Bromite as my browser and the Puffer app to block other ads and I still get the YouTube ads. Thanks

**Comment by aghontpi** [comment]
Hello @HonestAbe7, this app works using notification posted by the app, since "youtube/youtube music app" does not post notification, it can not be done.

however, you can try "https://github.com/YTVanced" ( not open source tho ).

**Comment by aghontpi** [comment]
I updated my previous reply, you are right about the youtube ads when viewed on browser and it should be doable. I'll investigate this further.

in the mean time, I strongly suggest you try newpipe - "https://github.com/TeamNewPipe/NewPipe/releases/" or newpipe with sponserblock "https://github.com/polymorphicshade/NewPipe/releases/". (both openSource)

**Comment by aghontpi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [browser youtube support](https://trello.com/c/frgBwlcc/33-browser-youtube-support)

**Comment by HonestAbe7** [comment]
Thanks for helping me with this. Good information. I started using AdAway instead and haven't seen any ads yet with the NewPipe Legacy app. I will try the sponsorblock version if I notice ads.

**Comment by aghontpi** [comment]
Im glad I could be of help.





an update~
I looked into the notification (i.e notification when accessing youtube in browser), there are a few problems..
 - there is no identifiable information to clearly distinguish the audio that is playing is an ad. (since m.youtube.com does not tell the notification that it is an ad)
    - intercepted and parsed it but not enough info 😞  
![notification_object](https://user-images.githubusercontent.com/18617846/147782199-0ffdab09-5b27-4468-832c-2bc3b744d0b0.png)
 - maybe video length can be used..but no. (some ads are short but others are not.)

Even If i Identify it as an ad, since the term browser is generic, I have to keep a list of all browsers and track their notifications or get a particular browser name from the user...which is leading to a rabbit hole... so Im archiving this request until there are new findings/ developments.
